flags: {}
packages:
- '.'
extra-deps:
- gloss-1.9.3.1
- gloss-rendering-1.9.3.1
- GLUT-2.7.0.2
- OpenGL-2.12.0.0
- GLURaw-1.5.0.1
- OpenGLRaw-2.4.1.0
- ObjectName-1.1.0.0
- pqueue-1.3.1
- reactive-banana-1.0.0.0
resolver: lts-3.1
